# ─────────────────────────────────────────────────────────────────────────────
# Cinnamon Ridge — Room Image Manifest Generator
# Run this script whenever you add or remove images from the rooms/ folders.
# It will regenerate room-manifest.js, which index.html reads automatically.
#
# Usage:  .\generate-manifest.ps1
# ─────────────────────────────────────────────────────────────────────────────

# Map each room id → its folder path (relative to this script's location)
$roomFolders = [ordered]@{
    'room-01' = 'rooms/Deluxe_Double_Room_Pool View'
    'room-02' = 'rooms/Deluxe_Double_Room_Panorama_View'
    'room-03' = 'rooms/Deluxe_Triple_Room_Panorama_View'
    'room-04' = 'rooms/Deluxe_Double_Room_Terrace'
}

$root   = $PSScriptRoot
$result = [ordered]@{}

foreach ($entry in $roomFolders.GetEnumerator()) {
    $roomId    = $entry.Key
    $folderRel = $entry.Value
    $folderAbs = Join-Path $root $folderRel

    if (-not (Test-Path $folderAbs)) {
        Write-Warning "Folder not found: $folderRel  (skipping $roomId)"
        $result[$roomId] = @()
        continue
    }

    # Collect JPG files only (case-insensitive), sort numerically by base name
    $jpgFiles = Get-ChildItem -Path $folderAbs -File |
        Where-Object { $_.Extension -match '^\.(jpg|jpeg)$' } |
        Sort-Object { [int]($_.BaseName -replace '\D','') } |
        ForEach-Object {
            # Use forward slashes for web paths
            ($folderRel + '/' + $_.Name) -replace '\\', '/'
        }

    $result[$roomId] = @($jpgFiles)
    Write-Host "  $roomId  →  $($jpgFiles.Count) image(s) in $folderRel"
}

# Serialize to a JS file: window.ROOM_IMAGES = { ... };
$lines = @('/* Auto-generated by generate-manifest.ps1 — do not edit manually */')
$lines += 'window.ROOM_IMAGES = {'

$keys = @($result.Keys)
for ($i = 0; $i -lt $keys.Count; $i++) {
    $key    = $keys[$i]
    $imgs   = $result[$key]
    $comma  = if ($i -lt $keys.Count - 1) { ',' } else { '' }

    if ($imgs.Count -eq 0) {
        $lines += "    `"$key`": []$comma"
    } else {
        $quoted = ($imgs | ForEach-Object { "`"$_`"" }) -join ', '
        $lines += "    `"$key`": [$quoted]$comma"
    }
}

$lines += '};'

$outputPath = Join-Path $root 'room-manifest.js'
$lines -join "`n" | Set-Content -Path $outputPath -Encoding UTF8

Write-Host ""
Write-Host "room-manifest.js written to: $outputPath" -ForegroundColor Green
Write-Host "Refresh index.html in your browser to see the updated images." -ForegroundColor Cyan
